name: HelloWorld
on: 
 workflow_dispatch:
  inputs: 
    logLevel: 
      description: 'Log level'
      required: true
      default: 'warning'
    tags: 
       description: 'Test scenario tags'

jobs:

  hello:
    runs-on: 'windows-latest'
    
  
    steps:
     - uses: actions/checkout@v6.0.2
     - run: echo "hello"
     
  
    

  
 
